"""Render the exact ALSAChain-managed portion of .asoundrc."""

from __future__ import annotations

from pathlib import Path

from .models import Profile, Stage

BEGIN_MARKER = "# BEGIN ALSACHAIN"
END_MARKER = "# END ALSACHAIN"
CROSSFEED = {"gentle": (700, 4.5), "normal": (700, 6), "strong": (650, 9.5)}


def quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def stage_name(profile: Profile, index: int, stage: Stage) -> str:
    return f"{profile.id}_stage_{index + 1:02d}_{stage.id}"


def status_pcm(profile: Profile, slave: str, status_dir: Path) -> str:
    target = f"{profile.id}_status_target"
    status = f"{profile.id}_status"
    return (
        f"pcm.{target} {{\n    type plug\n    slave.pcm {quote(slave)}\n}}\n\n"
        f"pcm.{status} {{\n    type alsachain_status\n"
        f"    status_path {quote(str(status_dir / f'{profile.id}.status'))}\n"
        f"    slave_name {quote(target)}\n}}"
    )


def render_stage(profile: Profile, stage: Stage, index: int, slave: str, caps_path: str, crossfeed_path: str) -> tuple[str, str]:
    output = stage_name(profile, index, stage)
    if stage.type == "equalizer":
        if not caps_path:
            raise ValueError("caps.so is unavailable")
        return output, (
            f"ctl.{stage.ctl_name} {{\n    type equal\n    controls {quote(stage.controls_path or '')}\n"
            f"    library {quote(caps_path)}\n    module \"Eq10\"\n    channels {profile.channels}\n}}\n\n"
            f"pcm.{output} {{\n    type equal\n    slave.pcm {quote(slave)}\n"
            f"    controls {quote(stage.controls_path or '')}\n    library {quote(caps_path)}\n"
            f"    module \"Eq10\"\n    channels {profile.channels}\n}}"
        )
    if stage.type == "gain":
        coefficient = 10 ** (float(stage.gain_db or 0) / 20)
        table = "\n".join(f"        {channel}.{channel} {coefficient}" for channel in range(profile.channels))
        return output, f"pcm.{output} {{\n    type route\n    slave.pcm {quote(slave)}\n    ttable {{\n{table}\n    }}\n}}"
    if not crossfeed_path:
        raise ValueError("bs2b LADSPA plugin is unavailable; install ladspa-bs2b first")
    settings = stage.settings
    values = CROSSFEED[settings] if isinstance(settings, str) else (settings or {})
    cutoff = values[0] if isinstance(values, tuple) else values["cutoff"]
    feed = values[1] if isinstance(values, tuple) else values["feed"]
    return output, (
        f"pcm.{output} {{\n    type ladspa\n    slave.pcm {quote(slave)}\n"
        f"    path {quote(str(Path(crossfeed_path).parent))}\n    plugins [\n        {{\n"
        f"            label bs2b\n            input {{\n                controls [ {cutoff} {feed} ]\n            }}\n"
        "        }\n    ]\n}"
    )


def render_block(profiles: list[Profile], caps_path: str, crossfeed_path: str, status_dir: Path) -> str:
    entries: list[str] = []
    for profile in profiles:
        if not profile.enabled:
            continue
        slave = profile.target
        definitions: list[str] = []
        if not profile.bitperfect and profile.stages:
            for index, stage in enumerate(profile.stages):
                slave, definition = render_stage(profile, stage, index, slave, caps_path, crossfeed_path)
                definitions.append(definition)
            description = " -> ".join("EQ" if stage.type == "equalizer" else stage.type.title() for stage in profile.stages)
        else:
            description = "BITPERFECT" if profile.bitperfect else "PROCESSED"
        public = (
            f"pcm.{profile.pcm_name} {{\n    type plug\n    slave.pcm {quote(f'{profile.id}_status')}\n"
            "    hint {\n        show on\n"
            f"        description {quote(f'ALSAChain {description}: {profile.display_name}')}\n    }}\n}}"
        )
        entries.append("\n\n".join([*definitions, status_pcm(profile, slave, status_dir), public]))
    body = "\n\n".join(entries)
    return f"{BEGIN_MARKER}\n# Generated by ALSAChainQT. Do not edit this block manually.\n\n{body}{'\n' if body else ''}{END_MARKER}\n"


def replace_managed_block(existing: str, block: str) -> str:
    start, end = existing.find(BEGIN_MARKER), existing.find(END_MARKER)
    if start == -1 and end == -1:
        return existing + ("" if not existing or existing.endswith("\n") else "\n") + block
    if start < 0 or end < start:
        raise ValueError("Malformed ALSAChain markers in .asoundrc")
    after = end + len(END_MARKER)
    if existing[after:].startswith("\n"):
        after += 1
    return existing[:start] + block + existing[after:]
